name: deploy

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      name:
        description: "awa"
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install
        run: npm install

      - name: Build
        run: npm run build:pro
        env:
          VITE_BASE: ${{ secrets.VITE_BASE }}

      # use https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-enable-built-in-jekyll-enable_jekyll
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: a3510377
          user_email: a102009102009@gmail.com
          commit_message: build${{ github.event.head_commit.message }}
          # cname:
